# Generated by Django 5.2 on 2026-06-29 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metup_bot", "0002_talk_state_choices_single_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donation",
            options={
                "verbose_name": "пожертвование",
                "verbose_name_plural": "пожертвования",
            },
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "verbose_name": "событие",
                "verbose_name_plural": "события",
            },
        ),
        migrations.AlterModelOptions(
            name="networkingprofile",
            options={
                "verbose_name": "профиль нетворкинга",
                "verbose_name_plural": "профили нетворкинга",
            },
        ),
        migrations.AlterModelOptions(
            name="question",
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
            },
        ),
        migrations.AlterModelOptions(
            name="talk",
            options={
                "verbose_name": "доклад",
                "verbose_name_plural": "доклады",
            },
        ),
        migrations.AlterModelOptions(
            name="telegramprofile",
            options={
                "verbose_name": "профиль Telegram",
                "verbose_name_plural": "профили Telegram",
            },
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "verbose_name": "роль пользователя",
                "verbose_name_plural": "роли пользователей",
            },
        ),
        migrations.AlterField(
            model_name="donation",
            name="amount_rub",
            field=models.IntegerField(verbose_name="сумма (руб.)"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="создано"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="paid_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="оплачено"
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="status",
            field=models.CharField(max_length=20, verbose_name="статус"),
        ),
        migrations.AlterField(
            model_name="donation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="yookassa_payment_id",
            field=models.CharField(
                max_length=64, verbose_name="ID платежа YooKassa"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="создано"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="event",
            name="is_current",
            field=models.BooleanField(default=False, verbose_name="текущее"),
        ),
        migrations.AlterField(
            model_name="event",
            name="starts_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="начало"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=128, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="networkingprofile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="о себе"),
        ),
        migrations.AlterField(
            model_name="networkingprofile",
            name="contact",
            field=models.CharField(max_length=128, verbose_name="контакт"),
        ),
        migrations.AlterField(
            model_name="networkingprofile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="создан"
            ),
        ),
        migrations.AlterField(
            model_name="networkingprofile",
            name="is_published",
            field=models.BooleanField(
                default=False, verbose_name="опубликован"
            ),
        ),
        migrations.AlterField(
            model_name="networkingprofile",
            name="stack",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="стек технологий"
            ),
        ),
        migrations.AlterField(
            model_name="networkingprofile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="обновлён"),
        ),
        migrations.AlterField(
            model_name="networkingprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="networking_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="создан"
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="is_answered",
            field=models.BooleanField(default=False, verbose_name="отвечен"),
        ),
        migrations.AlterField(
            model_name="question",
            name="talk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="metup_bot.talk",
                verbose_name="доклад",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(verbose_name="текст"),
        ),
        migrations.AlterField(
            model_name="talk",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="создано"
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="description",
            field=models.TextField(blank=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="talk",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="talks",
                to="metup_bot.event",
                verbose_name="событие",
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="order_index",
            field=models.IntegerField(
                default=0, verbose_name="порядковый номер"
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="scheduled_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="запланированное окончание"
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="scheduled_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="запланированное начало"
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="speaker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="talks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="докладчик",
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="state",
            field=models.CharField(
                choices=[
                    ("planned", "Запланирован"),
                    ("active", "Идёт"),
                    ("finished", "Завершён"),
                ],
                default="planned",
                max_length=20,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="talk",
            name="title",
            field=models.CharField(max_length=200, verbose_name="название"),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="telegram_id",
            field=models.BigIntegerField(
                unique=True, verbose_name="ID в Telegram"
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                max_length=64,
                verbose_name="имя пользователя в Telegram",
            ),
        ),
        migrations.AlterField(
            model_name="telegramprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="telegram_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="assigned_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="назначен"
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("guest", "Гость"),
                    ("speaker", "Докладчик"),
                    ("organizer", "Организатор"),
                ],
                max_length=20,
                verbose_name="роль",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
    ]
